apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-api-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: gateway
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gateway-alerts
spec:
  groups:
  - name: gateway.rules
    rules:
    - alert: HighGatewayErrorRate
      expr: rate(envoy_http_requests_total{status_code=~"5.."}[1m]) / rate(envoy_http_requests_total[1m]) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate on Gateway"
        description: "Error rate is {{ $value }} for gateway {{ $labels.gateway }}"