apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: voip-udp-route
  namespace: default
spec:
  parentRefs:
  - name: multi-protocol-gateway
    sectionName: udp
  rules:
  - backendRefs:
    - name: voip-service
      port: 5060