{{- if .Values.cert-manager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-prod
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.cert-manager.issuer.email }}
    server: {{ .Values.cert-manager.issuer.server }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: istio

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-wildcard-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
spec:
  secretName: wildcard-cert
  issuerRef:
    name: {{ .Release.Name }}-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.{{ .Values.global.domain }}"
{{- end }}