apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "gateway-api.fullname" . }}-http
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name | default "main-gateway" }}
    namespace: {{ .Release.Namespace }}
  rules:
  {{- range .Values.httpRoutes }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .path }}
    backendRefs:
    - name: {{ .service }}
      port: {{ .port }}
  {{- end }}